language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - MATH_LIB=gmp
    - MATH_LIB=bcmath

before_script:
    - composer selfupdate
    - composer install --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'


matrix:
    fast_finish: true
